const data = [
    { name: "Kousik Roy", time: "12:12 PM", message: "Hi this is my first Post" },
    { name: "Kousik Roy", time: "12:12 PM", message: "Hi this is my first Post" },
    { name: "Kousik Roy", time: "12:12 PM", message: "Hi this is my first Post" },
    { name: "Kousik Roy", time: "12:12 PM", message: "Hi this is my first Post" },
    { name: "Kousik Roy", time: "12:12 PM", message: "Hi this is my first Post" },
    { name: "Kousik Roy", time: "12:12 PM", message: "Hi this is my first Post" },
    { name: "Kousik Roy", time: "12:12 PM", message: "Hi this is my first Post" },
    { name: "Kousik Roy", time: "12:12 PM", message: "Hi this is my first Post" },
    { name: "Kousik Roy", time: "12:12 PM", message: "Hi this is my first Post" },
    { name: "Kousik Roy", time: "12:12 PM", message: "Hi this is my first Post" },
    { name: "Kousik Roy", time: "12:12 PM", message: "Hi this is my first Post" },
    { name: "Kousik Roy", time: "12:12 PM", message: "Hi this is my first Post" },
    { name: "Kousik Roy", time: "12:12 PM", message: "Hi this is my first Post" },
    { name: "Kousik Roy", time: "12:12 PM", message: "Hi this is my first Post" },
    { name: "Kousik Roy", time: "12:12 PM", message: "Hi this is my first Post" },
    { name: "Kousik Roy", time: "12:12 PM", message: "Hi this is my first Post" },
    { name: "Kousik Roy", time: "12:12 PM", message: "Hi this is my first Post" },
    { name: "Kousik Roy", time: "12:12 PM", message: "Hi this is my first Post" },
    { name: "Kousik Roy", time: "12:12 PM", message: "Hi this is my first Post" },
    { name: "Kousik Roy", time: "12:12 PM", message: "Hi this is my first Post" },
    { name: "Kousik Roy", time: "12:12 PM", message: "Hi this is my first Post" },
    { name: "Kousik Roy", time: "12:12 PM", message: "Hi this is my first Post" },
    { name: "Kousik Roy", time: "12:12 PM", message: "Hi this is my first Post" },
    { name: "Kousik Roy", time: "12:12 PM", message: "Hi this is my first Post" },
];
